baseURL = 'https://KwonPH.github.io/'
# 최신 휴고 버전의 권장 사항에 따라 수정합니다.
defaultContentLanguage = 'ko'
title = '권희범패시브건축'
theme = 'blowfish'

[params]
  colorScheme = "blowfish" 
  
  [params.header]
    layout = "fixed" 
    
  [params.footer]
    showCopyright = true
    showThemeAttribution = true