baseURL = 'https://KwonPH.github.io/'
# 최신 휴고 버전의 권장 사항에 따라 수정합니다.
defaultContentLanguage = 'ko'
title = '권희범패시브건축'
theme = 'blowfish'

[params]
  colorScheme = "blowfish" 
  # 아래 설정을 추가하여 배경 이미지를 명시적으로 지정합니다.
  homepage = { layout = "background", homepageImage = "background.jpg" }

[params.header]
    layout = "fixed" 
    showName = false # 상단 좌측의 사이트 이름을 숨깁니다.
    
[params.footer]
    showCopyright = true
    showThemeAttribution = false

[markup.goldmark.renderer]
  unsafe = true # 마크다운 내의 HTML(스타일 태그) 사용을 허용합니다.
